import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/navbar'
import { Toaster } from 'sonner'
import { AppProvider } from './provider'
import { Overlay } from '@/components/overlay/overlay'
import { getAuthenticatedUser } from '@/lib/auth'
import { ProfileFormModal } from '@/features/auth/components/profile-form-modal'
import { dehydrate, HydrationBoundary, QueryClient } from '@tanstack/react-query'
import { getProfileMeOptions } from '@/services/hooks/profile'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const queryClient = new QueryClient()

  const user = await getAuthenticatedUser()

  await queryClient.fetchQuery(getProfileMeOptions())
  const dehydratedState = dehydrate(queryClient)

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AppProvider initialUser={user}>
          <HydrationBoundary state={dehydratedState}>
            <ProfileFormModal />
            <Navbar />
            <Toaster />
            <Overlay />
            {children}
          </HydrationBoundary>
        </AppProvider>
      </body>
    </html>
  )
}
